sudo: required

services:
- docker
- docker-compose

# before_install:
# - apt update
# - apt install docker-compose

script:
- docker-compose up -d
- docker-compose exec ansible-master ansible all -m ping