sudo: required

services:
- docker
- docker-compose

before_install:
- sudo apt-get update
- docker-compose -v
- sudo apt-get install docker-compose

script:
- docker-compose up -d
- docker-compose exec ansible-master ansible all -m ping