version: "3.5"

networks:
  instances:
    driver: bridge
    name: instances

services:
  instance1:
    container_name: ubuntu1
    build: ./images/instance
    expose:
      - "22"
    networks:
      - instances

  instance2:
    container_name: ubuntu2
    build: ./images/instance
    expose:
      - "22"
    networks:
      - instances

  instance3:
    container_name: ubuntu3
    build: ./images/instance
    expose:
      - "22"
    networks:
      - instances

  instance4:
    container_name: ubuntu4
    build: ./images/instance
    expose:
      - "22"
    networks:
      - instances

  ansible-master:
    container_name: ansible
    build: ./images/ansible
    volumes:
      - type: bind
        source: ./playbooks
        target: /etc/playbooks
    tty: true
    depends_on:
      - instance1
      - instance2
      - instance3
      - instance4
    networks:
      - instances