version: "3.5"

networks:
  ansible-test:
    driver: bridge
    name: instances

services:
  instance1:
    container_name: ubuntu1
    # domainname: ubuntu1.com
    image: moreal/ubuntu-sshd:latest
    expose:
      - "22"
    networks:
      - ansible-test

  instance2:
    container_name: ubuntu2
    # domainname: ubuntu2.com
    image: moreal/ubuntu-sshd:latest
    expose:
      - "22"
    networks:
      - ansible-test

  instance3:
    container_name: ubuntu3
    # domainname: ubuntu3.com
    image: moreal/ubuntu-sshd:latest
    expose:
      - "22"
    networks:
      - ansible-test

  instance4:
    container_name: ubuntu4
    domainname: ubuntu4.com
    image: moreal/ubuntu-sshd:latest
    expose:
      - "22"
    networks:
      - ansible-test

  ansible-master:
    container_name: ansible
    domainname: ansible
    image: moreal/ubuntu-ansible:latest
    tty: true
    depends_on:
      - instance1
      - instance2
      - instance3
      - instance4
    networks:
      - ansible-test